name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/call-now:latest
          build-args: |
            NEXT_PUBLIC_BACKEND=https://api.hearme.life/
            PORT=5000
      
      - name: Verify Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/call-now:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo docker stop call-now || true
            sudo docker rm call-now || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/call-now:latest
            sudo docker run -d -p 5000:5000 -p 3000:3000 --name call-now --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/call-now:latest
            sudo docker image prune -f  
